<?php

/**
 * ProcessWire 404 Search Results Generator
 * by Adrian Jones
 *
 * Redirect 404 pages to search page with terms from failed URL
 *
 * ProcessWire 2.x
 * Copyright (C) 2011 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class Process404Search extends Process implements Module, ConfigurableModule {

    public static function getModuleInfo() {
        return array(
            'title' => '404 Search Results Generator',
            'summary' => 'Load search results into 404 page using terms from the failed URL',
            'href' => 'http://processwire.com/talk/topic/5724-404-search-module/',
            'version' => 8,
            'autoload' => true,
            'singular' => true
        );
    }


   /**
     * Default configuration for module
     *
     */
    static public function getDefaultData() {
            return array(
                "searchPage" => ""
            );
    }

    /**
     * Populate the default config data
     *
     */
    public function __construct() {
       foreach(self::getDefaultData() as $key => $value) {
               $this->$key = $value;
       }
    }


    public function init() {
        $this->addHookAfter('ProcessPageView::pageNotFound', $this, 'search', array('priority'=>1000));
    }

    public function search($event) {
        $request = parse_url($_SERVER['REQUEST_URI']);
        $path = $request["path"];
        $result = trim(str_replace(basename($_SERVER['SCRIPT_NAME']), '', $path), '/');
        $term = str_replace(array('-','_','/'),' ',$result);
        $event->return = $this->page->render($this->pages->get($this->searchPage)->template->filename, array('q' => $term));
    }


    public static function getModuleConfigInputfields(array $data) {

        $data = array_merge(self::getDefaultData(), $data);

        $form = new InputfieldWrapper();

        $fieldset = wire('modules')->get('InputfieldFieldset');
        $fieldset->label = '404 Search Results Generator';
        $fieldset->description = 'After you choose your search page in the field below, you must edit your search template (most likely search.php) and add this as the first line:
        if(isset($options[\'q\'])) $input->get->q = $options[\'q\'];

        Alternatively, you could use the following, to also include your "404 Page Not Found" page\'s body field. This needs to be after $out is initially defined in the search.php file:
        if(isset($options[\'q\'])){
        &nbsp;&nbsp;&nbsp;&nbsp;$input->get->q = $options[\'q\'];
        &nbsp;&nbsp;&nbsp;&nbsp;$out .= $pages->get(27)->body;
        }

        You may want to enter something like the following into your 404 Page Not Found page field:
        <h3>The page you were looking for is not found.</h3>
        <p>We have tried to find the content you were looking for, but if we didn\'t get it right, please use our search engine or navigation above to find the page.</p>';

        $f = wire('modules')->get("InputfieldPageListSelect");
        $f->name = 'searchPage';
        $f->label = 'Search Page';
        $f->required = true;
        $f->attr('value', $data["searchPage"]);
        $f->description = "Select your site's search page.";
        $fieldset->add($f);

        $form->add($fieldset);
        return $form;
    }

}